language: C
script: "./build.sh"
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libc6 libc6-dev multiarch-support
notifications:
  slack:
    secure: ugJ1l3dHJA0ojEYd7v34SEjqZxKugnKxLYA/HOI+2eb1Y8/QH7kgU+SJ3aiBFZrgh1bqdQhYpZyrLKgGN5fcLJC6ogP0rnxhzvrsR45W282WVyrtbRYeAuUrCIf53RiuTF95lVFuF9qLLU9M1C+GmvoBcbdKxhLVfBp8tQyTi7095yrUVtVZ4Z3K0kYNgBc1LPhiR0bA1IBqXUkfKl5AaIXiJH3s8cb1KFmay68J5YZ9ngKRrhgq6T1FBoSD1i3aNf1sPPgaHrCt55MPWB9JpvYbgpse5G6vjMiIXNVKoFMEuHO1qSfyZzLG1gRrh8SPE5AMNeGiDocn9X4IxUyK99IAvTR3w3Eqkh5nfg1+2iZBn4cNIZdEqSPbDpruSur0T8Wu2xgyjeP3uo01X08XOedyMCb7Nb9TgRkVr5TCBZ0BOaaHcaDnc6V5pSMSyWQPDYwNGXOLFI0Z9hnf2busu7MU3i1ArPw+OYXj/tT3SRUxIdrGrAZC7zu6KIrAhPtJ7wzWVk4cE+FkAKVI9Sfcob9F+of0Egz7PK4D0qcR/So+Pk2+7sOeVYWoD3MrBJefB6utkBIbuhKFaeLKK31rbUHXRpNcCk+TdobPAbepc3SUJkVGqMFARedU7mR7GV6Et+4/nMNA8YtXvhOk9UCUH2FlqwP+oiCqhd8mvuwyBvM=
