test:specsandtests/hw1Test.sh
	cp ${CURDIR}/java/vigenere.java ${CURDIR}/specsandtests/
	${CURDIR}/specsandtests/hw1Test.sh vigenere.java
	cd ..
	
clean:
	rm ${CURDIR}/specsandtests/stu*Output.txt
	rm ${CURDIR}/specsandtests/*.class
	rm ${CURDIR}/specsandtests/*.java
